services:
  pin-api:
    build: .
    restart: always
    expose:
      - "8000"
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true
    name: emotion-speech-recognition-api_default
